spring:
  application:
    name: Ski_school
  h2:
    console:
      enabled: true
      path: '/console'
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:h2:file:./ski_school-db'
  jpa:
    hibernate:
      ddl-auto: update



